package icia.js.lostandfound.utils;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSenderImpl;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;

import icia.js.lostandfound.beans.EmailBean;
@Component
public class EmailService {
	@Autowired
	private	JavaMailSenderImpl mail; 
	@Autowired
	private ProjectUtils util;
	@Value("${privateIp}")
	private String privateIp;
	
	public boolean sendEmail(EmailBean eb) {
		boolean result = false;
		
		MimeMessage javaMail = this.mail.createMimeMessage();
		MimeMessageHelper mailHelper = new MimeMessageHelper( javaMail, "UTF-8");
		
		try {
			for(int mailIdx = 0; mailIdx < eb.getReceiver().size(); mailIdx++ ) {

				mailHelper.setFrom(eb.getSender());
				mailHelper.setTo(eb.getReceiver().get(mailIdx)[1]);
				mailHelper.setSubject(eb.getSubject());
				mailHelper.setText(eb.getContents().get(mailIdx), eb.isHtml()); 

				this.mail.send(javaMail);
				result = true;
			}
		} catch (MessagingException e) {e.printStackTrace();}
		return result;
	}
	public String emailTemplate(String laName,String faName) {
		StringBuffer sb= new StringBuffer();
		sb.append("<!DOCTYPE html>\r\n"
				+ "\r\n"
				+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n"
				+ "<head>\r\n"
				+ "<title></title>\r\n"
				+ "<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\r\n"
				+ "<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\"/>\r\n"
				+ "<meta name=\"referrer\" content=\"no-referrer\">\r\n"
				+ "<!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
				+ "<!--[if !mso]><!-->\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Noto+Serif\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css2?family=Inter&family=Work+Sans:wght@700&display=swap\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "<link href=\"https://fonts.googleapis.com/css?family=Roboto+Slab\" rel=\"stylesheet\" type=\"text/css\"/>\r\n"
				+ "\r\n"
				+ "<!--<![endif]-->\r\n"
				+ "<style>\r\n"
				+ "		* {\r\n"
				+ "			box-sizing: border-box;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		body {\r\n"
				+ "			margin: 0;\r\n"
				+ "			padding: 0;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		a[x-apple-data-detectors] {\r\n"
				+ "			color: inherit !important;\r\n"
				+ "			text-decoration: inherit !important;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		#MessageViewBody a {\r\n"
				+ "			color: inherit;\r\n"
				+ "			text-decoration: none;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		p {\r\n"
				+ "			line-height: inherit\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.desktop_hide,\r\n"
				+ "		.desktop_hide table {\r\n"
				+ "			mso-hide: all;\r\n"
				+ "			display: none;\r\n"
				+ "			max-height: 0px;\r\n"
				+ "			overflow: hidden;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		.image_block img+div {\r\n"
				+ "			display: none;\r\n"
				+ "		}\r\n"
				+ "\r\n"
				+ "		@media (max-width:720px) {\r\n"
				+ "			.desktop_hide table.icons-inner {\r\n"
				+ "				display: inline-block !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner {\r\n"
				+ "				text-align: center;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.icons-inner td {\r\n"
				+ "				margin: 0 auto;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.image_block img.big,\r\n"
				+ "			.row-content {\r\n"
				+ "				width: 100% !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				display: none;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.stack .column {\r\n"
				+ "				width: 100%;\r\n"
				+ "				display: block;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.mobile_hide {\r\n"
				+ "				min-height: 0;\r\n"
				+ "				max-height: 0;\r\n"
				+ "				max-width: 0;\r\n"
				+ "				overflow: hidden;\r\n"
				+ "				font-size: 0px;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.desktop_hide,\r\n"
				+ "			.desktop_hide table {\r\n"
				+ "				display: table !important;\r\n"
				+ "				max-height: none !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-2 .column-2 .block-1.paragraph_block td.pad>div,\r\n"
				+ "			.row-4 .column-2 .block-2.paragraph_block td.pad>div {\r\n"
				+ "				text-align: center !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-2 .column-1,\r\n"
				+ "			.row-4 .column-1 {\r\n"
				+ "				padding: 20px 10px !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-2 .column-2 {\r\n"
				+ "				padding: 5px 25px 20px !important;\r\n"
				+ "			}\r\n"
				+ "\r\n"
				+ "			.row-4 .column-2 {\r\n"
				+ "				padding: 5px 30px 20px 25px !important;\r\n"
				+ "			}\r\n"
				+ "		}\r\n"
				+ "	</style>\r\n"
				+ "</head>\r\n"
				+ "<body style=\"background-color: #f7f7f7; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"nl-container\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f7f7f7;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; width: 700px;\" width=\"700\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<div class=\"spacer_block\" style=\"height:15px;line-height:15px;font-size:1px;\"> </div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #f7f7f7;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; background-color: #433a93; background-image: url('images/Header-bg.png'); background-repeat: no-repeat; background-size: cover; width: 700px;\" width=\"700\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 30px; padding-right: 10px; padding-top: 20px; vertical-align: middle; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><a style=\"outline:none\" tabindex=\"-1\" target=\"_blank\"><img alt=\"your-logo\" src=\"https://i.imgur.com/rMTa7o8.png\" style=\"display: block; height: auto; border: 0; width: 193px; max-width: 100%;\" title=\"your-logo\" width=\"193\"/></a></div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "<td class=\"column column-2\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-left: 25px; padding-right: 30px; padding-top: 5px; vertical-align: middle; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\">\r\n"
				+ "<div style=\"color:#ffffff;direction:ltr;font-family:Inter, sans-serif;font-size:16px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:right;mso-line-height-alt:19.2px;\"></div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #ffffff; color: #000000; width: 700px;\" width=\"700\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 35px; padding-left: 25px; padding-right: 25px; padding-top: 35px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"heading_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:20px;padding-top:5px;text-align:center;width:100%;\">\r\n"
				+ "<h1 style=\"margin: 0; color: #4f5aba; direction: ltr; font-family: 'Noto Serif', Georgia, serif; font-size: 38px; font-weight: 700; letter-spacing: normal; line-height: 120%; text-align: left; margin-top: 0; margin-bottom: 0;\"><span class=\"tinyMce-placeholder\">lost & found portal</span></h1>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><a style=\"outline:none\" tabindex=\"-1\" target=\"_blank\"><img alt=\"graduation\" class=\"big\" src=\"https://i.imgur.com/dmPpmp1.png\" style=\"display: block; height: auto; border: 0; width: 650px; max-width: 100%;\" title=\"graduation\" width=\"650\"/></a></div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-3\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-top:30px;\">\r\n"
				+ "<div style=\"color:#201f42;direction:ltr;font-family:'Roboto Slab', Arial, 'Helvetica Neue', Helvetica, sans-serif;font-size:18px;font-weight:400;letter-spacing:0px;line-height:180%;text-align:left;mso-line-height-alt:32.4px;\">\r\n"
				+ "<p style=\"margin: 0;\">분실물 : "+laName+"</p>\r\n"
				+ "</div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-top:30px;\">\r\n"
				+ "<div style=\"color:#201f42;direction:ltr;font-family:'Roboto Slab', Arial, 'Helvetica Neue', Helvetica, sans-serif;font-size:18px;font-weight:400;letter-spacing:0px;line-height:180%;text-align:left;mso-line-height-alt:32.4px;\">\r\n"
				+ "<p style=\"margin: 0;\">습득물 : "+faName+"</p>\r\n"
				+ "</div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-5\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-top:30px;\">\r\n"
				+ "<div style=\"color:#201f42;direction:ltr;font-family:'Roboto Slab', Arial, 'Helvetica Neue', Helvetica, sans-serif;font-size:18px;font-weight:400;letter-spacing:0px;line-height:180%;text-align:left;mso-line-height-alt:32.4px;\">\r\n"
				+ "<p style=\"margin: 0;\">키워드와 관련된 새로운 게시글이 올라왔습니다</p>\r\n"
				+ "</div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"button_block block-6\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"padding-bottom:15px;padding-top:30px;text-align:center;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\">\r\n"
				+ "<!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"http://"+privateIp+":8888\" style=\"height:44px;width:184px;v-text-anchor:middle;\" arcsize=\"0%\" strokeweight=\"0.75pt\" strokecolor=\"#201F42\" fillcolor=\"#201f42\"><w:anchorlock/><v:textbox inset=\"0px,0px,0px,0px\"><center style=\"color:#ffffff; font-family:Georgia, serif; font-size:16px\"><![endif]--><a href=\"http://"+privateIp+":8888\" style=\"text-decoration:none;display:inline-block;color:#ffffff;background-color:#201f42;border-radius:0px;width:auto;border-top:1px solid #201F42;font-weight:400;border-right:1px solid #201F42;border-bottom:1px solid #201F42;border-left:1px solid #201F42;padding-top:5px;padding-bottom:5px;font-family:'Noto Serif', Georgia, serif;font-size:16px;text-align:center;mso-border-alt:none;word-break:keep-all;\" target=\"_blank\"><span style=\"padding-left:30px;padding-right:30px;font-size:16px;display:inline-block;letter-spacing:normal;\"><span dir=\"ltr\" style=\"word-break: break-word; line-height: 32px;\">lost&found 이동</span></span></a>\r\n"
				+ "<!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\r\n"
				+ "</div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-4\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-size: auto;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; border-radius: 0; color: #000000; background-size: auto; background-color: #201f42; width: 700px;\" width=\"700\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 20px; padding-left: 30px; padding-right: 10px; padding-top: 20px; vertical-align: middle; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"33.333333333333336%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><a style=\"outline:none\" tabindex=\"-1\" target=\"_blank\"><img alt=\"your-logo\" src=\"https://i.imgur.com/rMTa7o8.png\" style=\"display: block; height: auto; border: 0; width: 155px; max-width: 100%;\" title=\"your-logo\" width=\"155\"/></a></div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "<td class=\"column column-2\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-left: 25px; padding-right: 30px; padding-top: 5px; vertical-align: middle; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"66.66666666666667%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"image_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"width:100%;padding-right:0px;padding-left:0px;\">\r\n"
				+ "<div align=\"center\" class=\"alignment\" style=\"line-height:10px\"><a style=\"outline:none\" tabindex=\"-1\" target=\"_blank\"><img alt=\"graduation guys\" class=\"big\" src=\"https://i.imgur.com/wIgJzip.png\" style=\"display: block; height: auto; border: 0; width: 412px; max-width: 100%;\" title=\"graduation guys\" width=\"412\"/></a></div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-2\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\">\r\n"
				+ "<div style=\"color:#ffffff;direction:ltr;font-family:Inter, sans-serif;font-size:14px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:right;mso-line-height-alt:16.8px;\">\r\n"
				+ "<p style=\"margin: 0;\">Copyright © 2023 Your Brand Here, All rights reserved.</p>\r\n"
				+ "</div>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td>\r\n"
				+ "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 700px;\" width=\"700\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"column column-1\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; padding-bottom: 5px; padding-top: 5px; vertical-align: top; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\" width=\"100%\">\r\n"
				+ "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"icons_block block-1\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"pad\" style=\"vertical-align: middle; padding-bottom: 5px; padding-top: 5px; color: #9d9d9d; font-family: inherit; font-size: 15px; text-align: center;\">\r\n"
				+ "<table cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
				+ "<tr>\r\n"
				+ "<td class=\"alignment\" style=\"vertical-align: middle; text-align: center;\">\r\n"
				+ "<!--[if vml]><table align=\"left\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"display:inline-block;padding-left:0px;padding-right:0px;mso-table-lspace: 0pt;mso-table-rspace: 0pt;\"><![endif]-->\r\n"
				+ "<!--[if !vml]><!-->\r\n"
				+ "<table cellpadding=\"0\" cellspacing=\"0\" class=\"icons-inner\" role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; display: inline-block; margin-right: -4px; padding-left: 0px; padding-right: 0px;\">\r\n"
				+ "<!--<![endif]-->\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table>\r\n"
				+ "</td>\r\n"
				+ "</tr>\r\n"
				+ "</tbody>\r\n"
				+ "</table><!-- End -->\r\n"
				+ "</body>\r\n"
				+ "</html>");
		
		return sb.toString();
	}
}
